import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { Link, useParams, useNavigate } from 'react-router-dom'
import { Container } from '../components/ui/Layout'
import { Button } from '../components/ui/Button'
import { formatPrice, formatProductName } from '../data/products'
import { useCart } from '../lib/cart'
import { API_BASE_URL } from '../lib/config'
import type { Product as CartProduct } from '../data/products'
import { 
  ChevronLeftIcon, 
  ShieldIcon, 
  TruckIcon, 
  CheckIcon, 
  HeartIcon,
  PhoneIcon
} from '../components/ui/Icons'

/* ───────────────────── Attribute Parsing ───────────────────── */

// Категории, для которых допустима легаси-эвристика разбора осей из НАЗВАНИЯ товара
// (механизм A2 ниже): их названия собирал админский конструктор групп по шаблону.
// Для новых категорий (например, стайлеров) regex по названию выдумывает мусорные оси
// («Память: 500» из «500 Вт») — они идут в простую ветку «цвет + атрибуты».
const LEGACY_ATTR_SLUGS = new Set([
  'smartphones',
  'laptops',
  'monobloki',
  'tablets',
  'watches',
  'smart-bands',
  'umnye-ochki',
  'headphones',
  'tv',
  'gaming',
  'accessories',
])

interface ParsedAttrs {
  storage: string | null
  connectivity: string | null
  ram: string | null
  color: string | null
}

/**
 * Extract structured attributes from a product name and color field.
 * Works with names generated by the admin group creator, e.g.:
 *   "Apple iPhone 17 Pro Max 256 ГБ SIM + eSIM, Cosmic Orange"
 *   "MacBook Pro 14 M4 Pro 16/512 ГБ, Space Black"
 */
function parseAttrsFromProduct(name: string, color?: string | null): ParsedAttrs {
  let ram: string | null = null

  // ── Laptop: name contains "N ГБ SSD" or "N ТБ SSD" (built by admin group creator) ──
  const ssdMatch = name.match(/(\d+)\s*(ГБ|GB|ТБ|TB)\s+SSD/i)
  if (ssdMatch) {
    const ssdUnit = /ТБ|TB/i.test(ssdMatch[2]) ? 'ТБ' : 'ГБ'
    const storage = `${ssdMatch[1]} ${ssdUnit}`
    // RAM is the last ГБ/ТБ number BEFORE the SSD match
    const beforeSsd = name.slice(0, ssdMatch.index ?? 0)
    const allRamMatches = [...beforeSsd.matchAll(/(\d+)\s*(ГБ|GB|ТБ|TB)/gi)]
    let connectivity: string | null = null
    if (allRamMatches.length > 0) {
      const last = allRamMatches[allRamMatches.length - 1]
      const unit = /ТБ|TB/i.test(last[2]) ? 'ТБ' : 'ГБ'
      ram = `${last[1]} ${unit}`
    }
    return { storage, connectivity, ram, color: color || null }
  }

  // ── Watch parsing ──
  const watchMatch = name.match(/(\d+\s*(?:мм|mm))/i);
  if (watchMatch && !name.toLowerCase().includes('ssd')) {
    const conn = watchMatch[1].trim();
    
    let stor: string | null = null;
    const idx = name.indexOf(watchMatch[1]) + watchMatch[1].length;
    let remainder = name.slice(idx);
    
    if (color && remainder.includes(color)) {
      remainder = remainder.replace(color, '');
    }
    remainder = remainder.replace(/,/g, '').trim();
    stor = remainder || null;
    
    return { storage: stor, connectivity: conn, ram, color: color || null };
  }

  // ── Regular (non-laptop) parsing ──
  let storage: string | null = null
  const pairWithUnits = name.match(/(\d+)\s*(ГБ|GB|ТБ|TB)\s*\/\s*(\d+)\s*(ГБ|GB|ТБ|TB)/i)
  if (pairWithUnits) {
    const ramUnit = /ТБ|TB/i.test(pairWithUnits[2]) ? 'ТБ' : 'ГБ'
    const storUnit = /ТБ|TB/i.test(pairWithUnits[4]) ? 'ТБ' : 'ГБ'
    ram = `${pairWithUnits[1]} ${ramUnit}`
    storage = `${pairWithUnits[3]} ${storUnit}`
  } else {
    const storageMatch = name.match(/(\d+)(?:\s*\/\s*(\d+))?\s*(ГБ|GB|ТБ|TB)/i)
    if (storageMatch) {
      if (storageMatch[2]) {
        ram = `${storageMatch[1]} ГБ`
        const unit = /ТБ|TB/i.test(storageMatch[3]) ? 'ТБ' : 'ГБ'
        storage = `${storageMatch[2]} ${unit}`
      } else {
        const num = storageMatch[1].replace(/\s/g, '')
        const unit = /ТБ|TB/i.test(storageMatch[3]) ? 'ТБ' : 'ГБ'
        storage = `${num} ${unit}`
      }
    } else {
      // Bare number as storage: "iPhone 18 pro 256 sim" → "256"
      // Iterate ALL numbers and pick the first one that looks like a storage size (32+)
      const allNumbers = [...name.matchAll(/\b(\d{2,4})\b/g)]
      for (const m of allNumbers) {
        const n = parseInt(m[1])
        // Typical storage values: 32, 64, 128, 256, 512, 1024, etc.
        // Skip small numbers that are likely model numbers (e.g. "18" in "iPhone 18")
        if (n >= 32 && n <= 9999) {
          // Make sure it's not followed by unit-like suffixes that indicate non-storage
          const afterIdx = (m.index ?? 0) + m[0].length
          const after = name.slice(afterIdx, afterIdx + 5)
          if (!/^\s*(мм|mm|мес|"|\'|шт|₽)/i.test(after)) {
            storage = m[1]
            break
          }
        }
      }
    }
  }

  // Connectivity: SIM/eSIM/WiFi patterns (order matters — most specific first)
  let connectivity: string | null = null
  const connPatterns: [RegExp, string][] = [
    [/SIM\s*\+\s*eSIM/i, 'SIM + eSIM'],
    [/sim\s*\+\s*esim/i, 'SIM + eSIM'],
    [/nano[- ]?SIM\s*\+\s*eSIM/i, 'SIM + eSIM'],
    [/Dual\s*SIM/i, 'Dual SIM'],
    [/WiFi\s*\+\s*Cellular/i, 'WiFi + Cellular'],
    [/Wi-Fi\s*\+\s*Cellular/i, 'WiFi + Cellular'],
    [/(?:только\s+)?eSIM\b/i, 'eSIM'],
    [/(?:только\s+)?(?:Wi-Fi|WiFi)\b(?!\s*\+)/i, 'WiFi'],
    [/\bsim\b(?!\s*\+)/i, 'SIM'],
  ]
  for (const [pattern, label] of connPatterns) {
    if (pattern.test(name)) { connectivity = label; break }
  }

  return { storage, connectivity, ram, color: color || null }
}

function sortStorageValues(values: string[]): string[] {
  const toGB = (s: string): number => {
    const m = s.match(/(\d+(?:\/(\d+))?)\s*(ГБ|ТБ)/i)
    if (m) {
      const n = m[2] ? parseInt(m[2]) : parseInt(m[1])
      return /ТБ/i.test(m[3]) ? n * 1024 : n
    }
    // Bare number (e.g. "256", "512")
    const bare = parseInt(s)
    return isNaN(bare) ? 0 : bare
  }
  return [...values].sort((a, b) => toGB(a) - toGB(b))
}

function normalizeWatchStrapSize(value: string | null | undefined): string | null {
  if (!value) return null
  const normalized = value.trim().replace(/\s*\/\s*/g, '/').toUpperCase()
  if (normalized === 'ONE SIZE' || normalized === 'ONESIZE') return 'ONE SIZE'
  if (normalized === 'ЕДИНЫЙ') return 'Единый'
  if (['S', 'M', 'L', 'S/M', 'M/L'].includes(normalized)) return normalized
  return value.trim()
}

function normalizeMemoryValue(value: string | null | undefined): string | null {
  if (!value) return null
  const trimmed = value.trim().replace(/\s+/g, ' ')
  const m = trimmed.match(/^(\d+)\s*(ГБ|GB|ТБ|TB)$/i)
  if (!m) return trimmed
  const unit = /тб|tb/i.test(m[2]) ? 'ТБ' : 'ГБ'
  return `${m[1]} ${unit}`
}

function sortWatchStrapSizes(values: Array<string | null>): Array<string | null> {
  const order = ['S', 'S/M', 'M', 'M/L', 'L', 'ONE SIZE', 'Единый']
  const uniq = Array.from(new Set(values.map(v => normalizeWatchStrapSize(v) || null)))
  return uniq.sort((a, b) => {
    if (a === null && b === null) return 0
    if (a === null) return 1
    if (b === null) return -1
    const ai = order.indexOf(a)
    const bi = order.indexOf(b)
    if (ai !== -1 || bi !== -1) {
      if (ai === -1) return 1
      if (bi === -1) return -1
      return ai - bi
    }
    return a.localeCompare(b, 'ru', { sensitivity: 'base' })
  })
}

const CSS_COLOR_MAP: Record<string, string> = {
  'черный': '#1c1c1e', 'black': '#1c1c1e', 'чёрный': '#1c1c1e',
  'белый': '#f5f5f7', 'white': '#f5f5f7',
  'серый': '#8e8e93', 'gray': '#8e8e93', 'grey': '#8e8e93', 'серебро': '#c7c7cc', 'серебристый': '#c7c7cc',
  'синий': '#0071e3', 'blue': '#0071e3',
  'голубой': '#5ac8fa', 'cyan': '#5ac8fa',
  'красный': '#ff3b30', 'red': '#ff3b30',
  'зеленый': '#34c759', 'зелёный': '#34c759', 'green': '#34c759',
  'желтый': '#ffd60a', 'жёлтый': '#ffd60a', 'yellow': '#ffd60a',
  'оранжевый': '#ff9f0a', 'orange': '#ff9f0a', 'рыжий': '#e8651a', 'cosmic orange': '#e8651a',
  'розовый': '#ff2d55', 'pink': '#ff2d55',
  'фиолетовый': '#bf5af2', 'purple': '#bf5af2', 'лаванда': '#c4a4e8', 'лавандовый': '#c4a4e8',
  'золотой': '#f5c518', 'gold': '#f5c518', 'золото': '#f5c518',
  'титан': '#8e8e93', 'titan': '#8e8e93', 'titanium': '#8e8e93',
  'natural': '#e8d5b7', 'натуральный': '#e8d5b7',
  'desert': '#c8a882', 'пустыня': '#c8a882',
  'космос': '#1c1c2e', 'starlight': '#f5f5ea',
  'deep blue': '#0a1930', 'midnight': '#1c1c2e',
  'space black': '#1c1c1e', 'графит': '#4a4a4a', 'graphite': '#4a4a4a',
}

function getColorSwatch(colorName: string): string | null {
  const lower = colorName.toLowerCase()
  for (const [key, val] of Object.entries(CSS_COLOR_MAP)) {
    if (lower.includes(key)) return val
  }
  if (/^#[0-9a-f]{3,8}$/i.test(colorName)) return colorName
  return null
}

/* ───────────────────── Image Lightbox ───────────────────── */
function ImageLightbox({
  images,
  startIndex,
  getUrl,
  onClose,
}: {
  images: string[]
  startIndex: number
  getUrl: (src: string) => string
  onClose: () => void
}) {
  const [index, setIndex] = useState(startIndex)
  const [zoomed, setZoomed] = useState(false)
  const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(null)
  const [translate, setTranslate] = useState({ x: 0, y: 0 })
  const [origin, setOrigin] = useState({ x: 50, y: 50 })
  const imgRef = useRef<HTMLImageElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  const multi = images.length > 1
  const src = getUrl(images[index])

  const goPrev = useCallback(() => {
    setZoomed(false)
    setTranslate({ x: 0, y: 0 })
    setIndex((p) => (p === 0 ? images.length - 1 : p - 1))
  }, [images.length])

  const goNext = useCallback(() => {
    setZoomed(false)
    setTranslate({ x: 0, y: 0 })
    setIndex((p) => (p === images.length - 1 ? 0 : p + 1))
  }, [images.length])

  // Keyboard handling
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
      if (e.key === 'ArrowLeft' && multi) goPrev()
      if (e.key === 'ArrowRight' && multi) goNext()
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [onClose, goPrev, goNext, multi])

  // Lock body scroll
  useEffect(() => {
    const prev = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = prev }
  }, [])

  // Swipe support
  const handleTouchStart = (e: React.TouchEvent) => {
    if (zoomed) return
    setDragStart({ x: e.touches[0].clientX, y: e.touches[0].clientY })
  }
  const handleTouchEnd = (e: React.TouchEvent) => {
    if (!dragStart || zoomed) return
    const dx = e.changedTouches[0].clientX - dragStart.x
    if (Math.abs(dx) > 60 && multi) {
      dx > 0 ? goPrev() : goNext()
    }
    setDragStart(null)
  }

  const handleImageClick = (e: React.MouseEvent<HTMLImageElement>) => {
    e.stopPropagation()
    if (zoomed) {
      setZoomed(false)
      setTranslate({ x: 0, y: 0 })
    } else {
      // Set zoom origin to click position
      const rect = (e.target as HTMLElement).getBoundingClientRect()
      const x = ((e.clientX - rect.left) / rect.width) * 100
      const y = ((e.clientY - rect.top) / rect.height) * 100
      setOrigin({ x, y })
      setZoomed(true)
    }
  }

  // Drag panning when zoomed
  const handleMouseDown = (e: React.MouseEvent) => {
    if (!zoomed) return
    e.preventDefault()
    setDragStart({ x: e.clientX - translate.x, y: e.clientY - translate.y })
  }
  const handleMouseMove = (e: React.MouseEvent) => {
    if (!zoomed || !dragStart) return
    setTranslate({ x: e.clientX - dragStart.x, y: e.clientY - dragStart.y })
  }
  const handleMouseUp = () => {
    if (zoomed) setDragStart(null)
  }

  return (
    <div
      className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/90 backdrop-blur-sm"
      onClick={onClose}
    >
      {/* Close */}
      <button
        onClick={onClose}
        className="absolute right-4 top-4 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-white/20"
        aria-label="Закрыть"
      >
        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>

      {/* Counter */}
      {multi && (
        <span className="absolute left-4 top-4 rounded-full bg-white/10 px-3 py-1 text-sm text-white">
          {index + 1} / {images.length}
        </span>
      )}

      {/* Prev */}
      {multi && (
        <button
          onClick={(e) => { e.stopPropagation(); goPrev() }}
          className="absolute left-2 top-1/2 z-10 flex h-12 w-12 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-white/20 sm:left-4"
          aria-label="Предыдущее фото"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
        </button>
      )}

      {/* Main image */}
      <div
        ref={containerRef}
        className="flex h-full w-full items-center justify-center"
        onClick={(e) => e.stopPropagation()}
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        style={{ cursor: zoomed ? 'grab' : 'zoom-in' }}
      >
        <img
          ref={imgRef}
          src={src}
          alt=""
          onClick={handleImageClick}
          draggable={false}
          className="max-h-[85vh] max-w-[90vw] select-none object-contain transition-transform duration-200"
          style={{
            transform: zoomed
              ? `scale(2.5) translate(${translate.x / 2.5}px, ${translate.y / 2.5}px)`
              : 'scale(1)',
            transformOrigin: `${origin.x}% ${origin.y}%`,
          }}
        />
      </div>

      {/* Next */}
      {multi && (
        <button
          onClick={(e) => { e.stopPropagation(); goNext() }}
          className="absolute right-2 top-1/2 z-10 flex h-12 w-12 -translate-y-1/2 items-center justify-center rounded-full bg-white/10 text-white transition hover:bg-white/20 sm:right-4"
          aria-label="Следующее фото"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-7 w-7" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
          </svg>
        </button>
      )}

      {/* Thumbnails strip */}
      {multi && (
        <div className="absolute bottom-4 left-1/2 z-10 flex -translate-x-1/2 gap-2 rounded-2xl bg-black/40 p-2">
          {images.map((img, i) => (
            <button
              key={i}
              onClick={(e) => { e.stopPropagation(); setZoomed(false); setTranslate({ x: 0, y: 0 }); setIndex(i) }}
              className={`h-14 w-14 flex-shrink-0 overflow-hidden rounded-lg border-2 transition ${
                i === index ? 'border-yellow-400' : 'border-transparent opacity-60 hover:opacity-100'
              }`}
            >
              <img src={getUrl(img)} alt="" className="h-full w-full object-cover" />
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
/* ───────────────────── End Lightbox ───────────────────── */

interface ProductImage {
  id: string
  product_id: string
  file_path: string
  url: string
  original_filename: string
  mime_type: string
  file_size: number
  sort_order: number
  is_main: boolean
  variant_color?: string | null
}

interface ApiProduct {
  id: string
  name: string
  slug: string
  brand: string | null
  category_id: string | null
  category?: { id: string; name: string; slug: string }
  price: number
  discount_price: number | null
  stock_quantity: number
  is_active: boolean
  is_featured: boolean
  main_image_url: string | null
  images?: ProductImage[]
  attributes?: Record<string, string | number | boolean | null>
  description: string | null
  short_description: string | null
  sku: string | null
  model: string | null
  color: string | null
  warranty_months: number | null
  condition: string | null
  created_at: string
  updated_at: string
  siblings?: ApiSibling[]
}

interface CategoryProductField {
  key: string
  label: string
  field_type: 'text' | 'number' | 'select' | 'boolean'
  placeholder: string
  options: string[]
  is_required: boolean
  is_variant: boolean
}

interface ApiSibling {
  id: string
  name: string
  slug: string
  color: string | null
  main_image_url: string | null
  price: number
  discount_price: number | null
  is_active: boolean
  attributes?: Record<string, string | number | boolean | null> | null
}

interface ApiVariant {
  id: string
  name: string
  sku: string | null
  price: number | null
  discount_price: number | null
  stock_quantity: number
  color: string | null
  storage: string | null
  size: string | null
  image_url: string | null
  sort_order: number
}

function isImageUrl(url?: string): boolean {
  if (!url) return false
  return url.startsWith('http') || url.startsWith('/api/media') || url.startsWith('/products') || url.startsWith('/uploads') || url.startsWith('/static')
}

function getImageUrl(url?: string): string {
  if (!url) return ''
  if (url.startsWith('/uploads') || url.startsWith('/static')) return `${API_BASE_URL}${url}`
  return url
}

export function ProductPage() {
  const params = useParams()
  const navigate = useNavigate()
  const { addItem } = useCart()
  const id = params.id ?? ''
  
  // Try local data first, then API
  const localProduct = null  // all data from API
  
  const [apiProduct, setApiProduct] = useState<ApiProduct | null>(null)
  const [loading, setLoading] = useState(!localProduct)
  const [quantity, setQuantity] = useState(1)
  const [stockWarning, setStockWarning] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState<'description' | 'specs' | 'reviews'>('description')
  const [activeImageIndex, setActiveImageIndex] = useState(0)
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [lightboxStartIndex, setLightboxStartIndex] = useState(0)
  const [variants, setVariants] = useState<ApiVariant[]>([])
  const [categoryFields, setCategoryFields] = useState<CategoryProductField[]>([])
  // Independent selection state — each attribute is chosen separately
  const [selectedColor, setSelectedColor] = useState<string | null>(null)
  const [selectedStorage, setSelectedStorage] = useState<string | null>(null)
  const [selectedSize, setSelectedSize] = useState<string | null>(null)

  // Touch swipe tracking
  const touchStartX = useRef(0)
  const touchStartY = useRef(0)
  const didSwipe = useRef(false)
  // Mirror of the images array for use inside event listeners
  const imagesRef = useRef<string[]>([])
  // Ref for the gallery container (needed for non-passive wheel listener)
  const galleryRef = useRef<HTMLDivElement>(null)
  const wheelDebounce = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Keyboard arrow navigation
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      const imgs = imagesRef.current
      if (imgs.length <= 1) return
      if (e.key === 'ArrowLeft') setActiveImageIndex(i => (i - 1 + imgs.length) % imgs.length)
      else if (e.key === 'ArrowRight') setActiveImageIndex(i => (i + 1) % imgs.length)
    }
    window.addEventListener('keydown', handleKey)
    return () => window.removeEventListener('keydown', handleKey)
  }, [])

  // Trackpad horizontal swipe (wheel events with deltaX)
  useEffect(() => {
    const el = galleryRef.current
    if (!el) return
    const handleWheel = (e: WheelEvent) => {
      const imgs = imagesRef.current
      if (imgs.length <= 1) return
      // Only handle predominantly horizontal scroll
      if (Math.abs(e.deltaX) < Math.abs(e.deltaY) * 0.6) return
      e.preventDefault()
      if (wheelDebounce.current) return
      if (e.deltaX > 15) {
        setActiveImageIndex(i => (i + 1) % imgs.length)
      } else if (e.deltaX < -15) {
        setActiveImageIndex(i => (i - 1 + imgs.length) % imgs.length)
      }
      wheelDebounce.current = setTimeout(() => { wheelDebounce.current = null }, 550)
    }
    el.addEventListener('wheel', handleWheel, { passive: false })
    return () => el.removeEventListener('wheel', handleWheel)
  }, [apiProduct?.id]) // re-attach once the gallery div is in the DOM (after product loads)

  // Derive best-matching variant from the 3 independent selections
  const selectedVariant = useMemo<ApiVariant | null>(() => {
    if (variants.length === 0) return null
    // Exact match
    const exact = variants.find(v =>
      (!selectedColor || v.color === selectedColor) &&
      (!selectedStorage || v.storage === selectedStorage) &&
      (!selectedSize || v.size === selectedSize)
    )
    if (exact) return exact
    // Progressively relax — color + storage
    if (selectedColor && selectedStorage) {
      const m = variants.find(v => v.color === selectedColor && v.storage === selectedStorage)
      if (m) return m
    }
    // Color only
    if (selectedColor) {
      const m = variants.find(v => v.color === selectedColor)
      if (m) return m
    }
    return variants[0]
  }, [variants, selectedColor, selectedStorage, selectedSize])
  
  // Load from API — always try slug first (reliable), then fallback to numeric id
  useEffect(() => {
    // Reset state when navigating between sibling products
    setActiveImageIndex(0)
    setQuantity(1)
    setStockWarning(null)
    setVariants([])
    setSelectedColor(null)
    setSelectedStorage(null)
    setSelectedSize(null)
    setLoading(true)

    async function loadProduct() {
      try {
        // Try by slug first — this is the reliable way
        let res = await fetch(`${API_BASE_URL}/api/products/slug/${id}`)
        if (!res.ok) {
          // Fallback: maybe it's a numeric id
          res = await fetch(`${API_BASE_URL}/api/products/${id}`)
        }
        if (res.ok) {
          const data = await res.json()
          setApiProduct(data)
        }
      } catch (err) {
        console.error('Error loading product:', err)
      } finally {
        setLoading(false)
      }
    }
    
    loadProduct()
  }, [id])

  // Load variants once apiProduct is known
  useEffect(() => {
    if (!apiProduct) return
    fetch(`${API_BASE_URL}/api/products/${apiProduct.id}/variants`)
      .then(res => res.ok ? res.json() : [])
      .then((data: ApiVariant[]) => {
        setVariants(data)
        if (data.length > 0) {
          setSelectedColor(data[0].color ?? null)
          setSelectedStorage(data[0].storage ?? null)
          setSelectedSize(data[0].size ?? null)
        }
      })
      .catch(() => {})
  }, [apiProduct?.id])

  useEffect(() => {
    if (!apiProduct?.category_id) {
      setCategoryFields([])
      return
    }
    fetch(`${API_BASE_URL}/api/categories/${apiProduct.category_id}`)
      .then(res => res.ok ? res.json() : null)
      .then(category => setCategoryFields(category?.product_fields ?? []))
      .catch(() => setCategoryFields([]))
  }, [apiProduct?.category_id])

  // The catalog price is the source of truth for the whole purchase flow.
  // Variants only change the selected configuration, stock and image.
  const effectivePrice = apiProduct?.discount_price ?? apiProduct?.price ?? 0
  const effectiveOldPrice = apiProduct?.discount_price ? apiProduct.price : null
  const effectiveStock = selectedVariant?.stock_quantity ?? apiProduct?.stock_quantity ?? 0
  // Image: first look for a color-specific photo, then fall back to product main photo
  const effectiveImage = useMemo(() => {
    if (selectedColor) {
      const colorImg = variants.find(v => v.color === selectedColor && v.image_url)?.image_url
      if (colorImg) return colorImg
    }
    return selectedVariant?.image_url || (apiProduct && apiProduct.main_image_url) || null
  }, [selectedColor, variants, selectedVariant, apiProduct])
  
  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-yellow-400 border-t-transparent"></div>
      </div>
    )
  }
  
  if (!apiProduct) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center px-4">
        <div className="text-center">
          <div className="mb-6 text-6xl">🔍</div>
          <h1 className="mb-2 text-2xl font-bold text-gray-900">Товар не найден</h1>
          <p className="mb-6 text-gray-500">Возможно, товар был удален или вы ошиблись адресом</p>
          <Button to="/catalog">Перейти в каталог</Button>
        </div>
      </div>
    )
  }
  
  const handleAddToCart = () => {
      // Variant-aware name: append variant name if selected
      const baseName = formatProductName(apiProduct!.name)
      const productName = selectedVariant
        ? `${baseName} — ${selectedVariant.name}`
        : baseName

      const variantSpecs: Array<{label: string; value: string}> = []
      const isTvCategory = apiProduct?.category?.slug === 'tv'
      const isWatchCategory = apiProduct?.category?.slug === 'watches' || apiProduct?.category?.slug === 'smart-bands'
      // Лейблы осей — из схемы категории (product_fields), фолбэк на прежние захардкоженные.
      const fieldLabel = (key: string, fallback: string): string =>
        categoryFields.find(field => field.key === key)?.label || fallback
      if (selectedVariant?.color) variantSpecs.push({ label: fieldLabel('color', 'Цвет'), value: selectedVariant.color })
      if (selectedVariant?.storage) variantSpecs.push({ label: fieldLabel('storage', isTvCategory ? 'Диагональ' : isWatchCategory ? 'Размер ремешка' : 'Память'), value: selectedVariant.storage })
      if (selectedVariant?.size) variantSpecs.push({ label: fieldLabel('size', isWatchCategory ? 'Размер корпуса' : 'Размер'), value: selectedVariant.size })

      const cartProduct: CartProduct = {
        id: apiProduct!.id,
        slug: apiProduct!.slug,
        name: productName,
        brand: apiProduct!.brand || '',
        category: '',
        categorySlug: '',
        price: Number(effectivePrice),
        oldPrice: effectiveOldPrice != null ? Number(effectiveOldPrice) : undefined,
        inStock: effectiveStock > 0,
        stockQuantity: effectiveStock,
        image: effectiveImage || '📦',
        description: apiProduct!.description || '',
        condition: apiProduct!.condition || 'new',
        specs: [
          apiProduct!.brand && { label: 'Бренд', value: apiProduct!.brand },
          apiProduct!.model && { label: 'Модель', value: apiProduct!.model },
          ...variantSpecs,
        ].filter(Boolean) as Array<{label: string; value: string}>
      }

      for (let i = 0; i < quantity; i++) {
        addItem(cartProduct)
      }

      navigate('/cart')
    }

    // Build image URL list from ProductDetailOut images array
    // When a color is selected, show ONLY that color's photos (main first, then by sort_order)
    const images: string[] = (() => {
      if (!apiProduct.images?.length) {
        return apiProduct.main_image_url ? [apiProduct.main_image_url] : []
      }
      const allImgs = apiProduct.images

      if (selectedColor) {
        // Show only this color's photos, sorted: is_main first, then by sort_order
        const colorImgs = allImgs
          .filter(img => img.variant_color === selectedColor)
          .sort((a, b) => {
            if (a.is_main && !b.is_main) return -1
            if (!a.is_main && b.is_main) return 1
            return a.sort_order - b.sort_order
          })
        if (colorImgs.length > 0) {
          return colorImgs.map(img => img.url || img.file_path)
        }
      }

      // No color selected: try to find first color with photos, or show all sorted
      const colorsWithPhotos = [...new Set(allImgs.filter(img => img.variant_color).map(img => img.variant_color!))]
      if (colorsWithPhotos.length > 0) {
        // Show first available color's photos
        const firstColor = colorsWithPhotos[0]
        const firstColorImgs = allImgs
          .filter(img => img.variant_color === firstColor)
          .sort((a, b) => {
            if (a.is_main && !b.is_main) return -1
            if (!a.is_main && b.is_main) return 1
            return a.sort_order - b.sort_order
          })
        return firstColorImgs.map(img => img.url || img.file_path)
      }

      // No color photos at all: show generic photos sorted by main first
      const generic = allImgs
        .filter(img => !img.variant_color)
        .sort((a, b) => {
          if (a.is_main && !b.is_main) return -1
          if (!a.is_main && b.is_main) return 1
          return a.sort_order - b.sort_order
        })
      return generic.length > 0
        ? generic.map(img => img.url || img.file_path)
        : allImgs.map(img => img.url || img.file_path)
    })()

    // Keep ref in sync so keyboard/swipe handlers always see current images
    imagesRef.current = images
    
    return (
      <div className="min-h-screen bg-gray-50">
        {/* Breadcrumbs */}
        <div className="border-b border-gray-100 bg-white">
          <Container className="py-4">
            <nav className="flex items-center gap-2 text-sm">
              <Link to="/" className="text-gray-500 hover:text-yellow-600">Главная</Link>
              <span className="text-gray-300">/</span>
              <Link to="/catalog" className="text-gray-500 hover:text-yellow-600">Каталог</Link>
              <span className="text-gray-300">/</span>
              <span className="truncate text-gray-900">{formatProductName(apiProduct.name)}</span>
            </nav>
          </Container>
        </div>
        
        {/* Main Product Section */}
        <section className="bg-white py-8">
          <Container>
            <div className="grid gap-8 lg:grid-cols-2 lg:gap-12">
              {/* Product Image */}
              <div className="relative">
                <button
                  onClick={() => navigate(-1)}
                  className="absolute -left-4 -top-4 z-10 flex items-center gap-1 rounded-lg p-2 text-sm font-medium text-gray-500 transition-colors hover:text-gray-900 lg:hidden"
                >
                  <ChevronLeftIcon className="h-5 w-5" />
                  Назад
                </button>
                
                <div
                  ref={galleryRef}
                  className="relative overflow-hidden rounded-3xl bg-white group"
                >
                  {/* Badge */}
                  {apiProduct.is_featured && (
                    <div className="absolute left-4 top-4 z-10">
                      <span className="rounded-full bg-yellow-400 px-4 py-1.5 text-sm font-semibold text-gray-900">
                        Хит
                      </span>
                    </div>
                  )}
                  {apiProduct.discount_price && (
                    <div className={`absolute left-4 ${apiProduct.is_featured ? 'top-14' : 'top-4'} z-10`}>
                      <span className="rounded-full bg-red-500 px-4 py-1.5 text-sm font-semibold text-white">
                        -{Math.round((1 - apiProduct.discount_price / apiProduct.price) * 100)}%
                      </span>
                    </div>
                  )}

                  {/* Sliding strip */}
                  <div
                    className="flex aspect-square select-none"
                    style={{
                      transform: `translateX(-${activeImageIndex * 100}%)`,
                      transition: 'transform 0.42s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                    }}
                    onTouchStart={(e) => {
                      touchStartX.current = e.touches[0].clientX
                      touchStartY.current = e.touches[0].clientY
                      didSwipe.current = false
                    }}
                    onTouchEnd={(e) => {
                      const deltaX = e.changedTouches[0].clientX - touchStartX.current
                      const deltaY = e.changedTouches[0].clientY - touchStartY.current
                      const imgs = imagesRef.current
                      if (imgs.length > 1 && Math.abs(deltaX) > Math.abs(deltaY) && Math.abs(deltaX) > 40) {
                        didSwipe.current = true
                        if (deltaX < 0) setActiveImageIndex(i => (i + 1) % imgs.length)
                        else setActiveImageIndex(i => (i - 1 + imgs.length) % imgs.length)
                      }
                    }}
                  >
                    {images.map((img, i) => (
                      <div
                        key={i}
                        className="min-w-full flex items-center justify-center p-8 cursor-pointer"
                        onClick={() => {
                          if (didSwipe.current) return
                          if (isImageUrl(img)) {
                            setLightboxStartIndex(i)
                            setLightboxOpen(true)
                          }
                        }}
                      >
                        {isImageUrl(img) ? (
                          <img
                            src={getImageUrl(img)}
                            alt={apiProduct.name}
                            className="max-h-full max-w-full object-contain"
                            draggable={false}
                          />
                        ) : (
                          <span className="text-[12rem]">{img || '📦'}</span>
                        )}
                      </div>
                    ))}
                  </div>

                  {/* Dot indicators */}
                  {images.length > 1 && (
                    <div className="absolute bottom-3 left-1/2 -translate-x-1/2 flex gap-1.5 z-10">
                      {images.map((_, i) => (
                        <button
                          key={i}
                          onClick={() => setActiveImageIndex(i)}
                          className={`rounded-full transition-all duration-300 ${
                            i === activeImageIndex
                              ? 'w-5 h-1.5 bg-gray-800'
                              : 'w-1.5 h-1.5 bg-gray-400/60 hover:bg-gray-500'
                          }`}
                        />
                      ))}
                    </div>
                  )}

                  {/* Prev / Next arrow buttons — slide in from sides on hover */}
                  {images.length > 1 && (
                    <>
                      <button
                        onClick={(e) => { e.stopPropagation(); setActiveImageIndex(i => (i - 1 + images.length) % images.length) }}
                        className="absolute left-3 top-1/2 -translate-y-1/2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/90 shadow-md backdrop-blur-sm transition-all duration-250 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 hover:bg-white hover:shadow-lg"
                        aria-label="Предыдущее фото"
                      >
                        <svg className="w-5 h-5 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                        </svg>
                      </button>
                      <button
                        onClick={(e) => { e.stopPropagation(); setActiveImageIndex(i => (i + 1) % images.length) }}
                        className="absolute right-3 top-1/2 -translate-y-1/2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/90 shadow-md backdrop-blur-sm transition-all duration-250 opacity-0 translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 hover:bg-white hover:shadow-lg"
                        aria-label="Следующее фото"
                      >
                        <svg className="w-5 h-5 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                      </button>
                    </>
                  )}

                  {/* Favorite button */}
                  <button className="absolute right-4 top-4 rounded-full bg-white p-3 shadow-lg transition-colors hover:bg-yellow-50">
                    <HeartIcon className="h-6 w-6 text-gray-400 hover:text-red-500" />
                  </button>
                </div>
                
                {/* Image thumbnails */}
                {images.length > 1 && (
                  <div className="mt-4 flex gap-2 overflow-x-auto pb-2">
                    {images.map((img, i) => (
                      <button
                        key={i}
                        onClick={() => setActiveImageIndex(i)}
                        className={`relative h-20 w-20 flex-shrink-0 overflow-hidden rounded-xl border-2 transition-colors ${
                          i === activeImageIndex ? 'border-yellow-400' : 'border-gray-200 hover:border-gray-300'
                        }`}
                      >
                        {isImageUrl(img) ? (
                          <img src={getImageUrl(img)} alt="" className="h-full w-full object-cover" />
                        ) : (
                          <span className="flex h-full w-full items-center justify-center text-3xl bg-gray-100">{img}</span>
                        )}
                      </button>
                    ))}
                  </div>
                )}

                {/* Zoom hint */}
                {isImageUrl(images[activeImageIndex]) && (
                  <p className="mt-2 text-center text-xs text-gray-400">
                    {images.length > 1 ? 'Листайте пальцем или стрелками · нажмите для увеличения' : 'Нажмите на фото для увеличения'}
                  </p>
                )}

                {/* Lightbox */}
                {lightboxOpen && (
                  <ImageLightbox
                    images={images.filter(isImageUrl)}
                    startIndex={Math.min(lightboxStartIndex, images.filter(isImageUrl).length - 1)}
                    getUrl={getImageUrl}
                    onClose={() => setLightboxOpen(false)}
                  />
                )}
              </div>
              
              {/* Product Info */}
              <div className="flex flex-col">
                {/* Brand */}
                <div className="mb-2 flex items-center gap-2 text-sm">
                  <span className="text-yellow-600">{apiProduct.brand || ''}</span>
                </div>
                
                {/* Name */}
                <h1 className="mb-4 text-2xl font-bold text-gray-900 sm:text-3xl lg:text-4xl">
                  {formatProductName(apiProduct.name).replace(/\s*\([A-Z][A-Z0-9]{3,}\)$/, '')}
                  {(() => {
                    const m = apiProduct.name.match(/\(([A-Z][A-Z0-9]{3,})\)$/)
                    return m ? (
                      <span className="ml-3 align-middle inline-block rounded-lg bg-gray-100 px-2.5 py-1 text-sm font-mono font-normal text-gray-400">{m[1]}</span>
                    ) : null
                  })()}
                </h1>
                
                {/* Stock status */}
                <div className="mb-4">
                  {effectiveStock > 0 ? (
                    <span className="inline-flex items-center gap-1.5 text-sm text-green-600">
                      <CheckIcon className="h-4 w-4" />
                      В наличии
                    </span>
                  ) : (
                    <span className="text-sm text-red-500">Нет в наличии</span>
                  )}
                </div>

                {/* ── Group navigation: switch between linked product cards ── */}
                {apiProduct.siblings && apiProduct.siblings.length > 0 && (() => {
                  // All products in group: current + siblings
                  const allCards = [
                    { id: apiProduct.id, name: apiProduct.name, slug: apiProduct.slug, color: apiProduct.color, main_image_url: apiProduct.main_image_url, price: apiProduct.price, discount_price: apiProduct.discount_price, is_active: true, attributes: apiProduct.attributes, category: apiProduct.category, brand: apiProduct.brand },
                    ...apiProduct.siblings.map(s => ({
                      ...s,
                      brand: (s as any).brand ?? apiProduct.brand,
                      category: (s as any).category ?? apiProduct.category,
                    })),
                  ]

                  // Механизм A1: у категории в админке заданы вариантные поля (is_variant) —
                  // универсальный селектор строго по схеме категории, без угадывания из названий.
                  const variantFields = categoryFields.filter(field => field.is_variant)
                  if (variantFields.length > 0) {
                    const getValue = (card: typeof allCards[number], key: string): string => {
                      const value = key === 'color' ? card.color : card.attributes?.[key]
                      if (value === null || value === undefined || value === '') return ''
                      return typeof value === 'boolean' ? (value ? 'Да' : 'Нет') : String(value)
                    }
                    const currentValues = Object.fromEntries(variantFields.map(field => [field.key, getValue(allCards[0], field.key)]))
                    const goToValue = (fieldKey: string, value: string) => {
                      const wanted = { ...currentValues, [fieldKey]: value }
                      const match = allCards.find(card => card.id !== apiProduct.id && variantFields.every(field => {
                        const expected = wanted[field.key]
                        return !expected || getValue(card, field.key) === expected
                      })) || allCards.find(card => card.id !== apiProduct.id && getValue(card, fieldKey) === value)
                      if (match) navigate(`/product/${match.slug}`)
                    }
                    return (
                      <div className="mb-6 space-y-4">
                        {variantFields.map(field => {
                          const values = [...new Set(allCards.map(card => getValue(card, field.key)).filter(Boolean))]
                          const current = currentValues[field.key]
                          if (values.length === 0) return null
                          return (
                            <div key={field.key}>
                              <p className="mb-2 text-sm text-gray-500">{field.label}: <span className="font-semibold text-gray-900">{current || '—'}</span></p>
                              <div className="flex flex-wrap gap-2">
                                {values.map(value => {
                                  const isCurrent = value === current
                                  return <button key={value} onClick={() => !isCurrent && goToValue(field.key, value)} className={`rounded-xl border px-4 py-2 text-sm font-medium transition-all ${isCurrent ? 'border-gray-900 bg-gray-900 text-white shadow-sm' : 'border-gray-200 bg-white text-gray-700 hover:border-gray-400'}`}>{value}</button>
                                })}
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    )
                  }

                  // Гейт легаси-эвристики: разбор осей из названия (A2) — только для старых
                  // категорий из LEGACY_ATTR_SLUGS. Пустой slug тоже оставляем в A2 — так
                  // ведут себя старые товары без проставленной категории (например, очки).
                  const categorySlugLower = String(apiProduct.category?.slug || '').toLowerCase()
                  const isLegacyAttrCategory = categorySlugLower === '' || LEGACY_ATTR_SLUGS.has(categorySlugLower)

                  if (!isLegacyAttrCategory) {
                    // Новая категория без вариантных полей: честный переключатель только по
                    // цвету (реальные card.color сиблингов) + остальные атрибуты простым
                    // списком, как у одиночного товара. Никаких выдуманных осей из названия.
                    const simpleColors = [...new Set(allCards.map(card => card.color).filter(Boolean))] as string[]
                    const simpleCurrentColor = apiProduct.color || null
                    const goToColor = (color: string) => {
                      const match = allCards.find(card => card.id !== apiProduct.id && card.color === color)
                      if (match) navigate(`/product/${match.slug}`)
                    }
                    const attrLabels = new Map(categoryFields.map(field => [field.key, field.label]))
                    const attrRows: { label: string; value: string }[] = []
                    Object.entries(apiProduct.attributes || {}).forEach(([key, value]) => {
                      if (value === null || value === undefined || value === '') return
                      attrRows.push({
                        label: attrLabels.get(key) || key.replace(/_/g, ' '),
                        value: typeof value === 'boolean' ? (value ? 'Да' : 'Нет') : String(value),
                      })
                    })
                    if (simpleColors.length === 0 && attrRows.length === 0) return null
                    return (
                      <div className="mb-6 space-y-4">
                        {simpleColors.length > 0 && (
                          <div>
                            <p className="mb-2 text-sm text-gray-500">
                              Цвет: <span className="font-semibold text-gray-900">{simpleCurrentColor || '—'}</span>
                            </p>
                            <div className="flex flex-wrap items-center gap-2.5">
                              {simpleColors.map(color => {
                                const isCurrent = color === simpleCurrentColor
                                const swatch = getColorSwatch(color)
                                const isLight = swatch ? parseInt(swatch.replace('#', '').slice(0, 2), 16) > 200 : false
                                const sibForColor = allCards.find(card => card.color === color)
                                const thumb = sibForColor?.main_image_url
                                return (
                                  <button
                                    key={color}
                                    title={color}
                                    onClick={() => !isCurrent && goToColor(color)}
                                    className={`group relative flex flex-col items-center gap-1 rounded-xl border-2 p-1.5 transition-all ${
                                      isCurrent
                                        ? 'border-gray-900 bg-gray-50 shadow-sm'
                                        : 'border-gray-200 bg-white hover:border-gray-400 hover:shadow-sm cursor-pointer'
                                    }`}
                                    style={{ minWidth: 56 }}
                                  >
                                    {thumb && isImageUrl(thumb) ? (
                                      <div className="h-12 w-12 overflow-hidden rounded-lg bg-gray-100">
                                        <img src={getImageUrl(thumb)} alt={color} className="h-full w-full object-contain" />
                                      </div>
                                    ) : swatch ? (
                                      <div
                                        className={`h-12 w-12 rounded-lg ${isLight ? 'ring-1 ring-inset ring-gray-200' : ''}`}
                                        style={{ backgroundColor: swatch }}
                                      />
                                    ) : (
                                      <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gray-100 text-xs text-gray-400">
                                        {color.slice(0, 3)}
                                      </div>
                                    )}
                                    <span className={`max-w-[70px] truncate text-[10px] leading-tight ${
                                      isCurrent ? 'font-semibold text-gray-900' : 'text-gray-500 group-hover:text-gray-700'
                                    }`}>
                                      {color}
                                    </span>
                                  </button>
                                )
                              })}
                            </div>
                          </div>
                        )}
                        {attrRows.length > 0 && (
                          <div className="space-y-2">
                            {attrRows.map(({ label, value }) => (
                              <div key={label}>
                                <span className="text-sm text-gray-500">{label}: </span>
                                <span className="text-sm font-semibold text-gray-900">{value}</span>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    )
                  }

                  // Механизм A2 (легаси): разбор осей из названия/attributes конструктора групп.
                  const getParsed = (item: any) => {
                    const attrs = item.attributes || {};
                    if (Object.keys(attrs).length > 0 && (attrs.storage || attrs.connectivity || attrs.processor)) {
                      const brand = String(item.brand || '').toLowerCase()
                      const categorySlug = String(item.category?.slug || '').toLowerCase()
                      const connectivityRaw = String(attrs.connectivity || '')
                      const processorRaw = String(attrs.processor || '')
                      const storageRaw = String(attrs.storage || '')
                      const isMemoryLike = (v: string) => /\d+\s*(гб|gb|тб|tb)/i.test(v)
                      const isSimLike = (v: string) => /sim|esim|wi[-\s]?fi|cellular/i.test(v)
                      const isPhoneByName = /смартфон|galaxy|iphone|xiaomi|redmi|poco|pixel|oneplus|huawei|honor|z\s*fold|z\s*flip/i.test(String(item.name || '').toLowerCase())
                      const inferredRamAxisPhone =
                        isMemoryLike(connectivityRaw) &&
                        (isSimLike(processorRaw) || (isPhoneByName && processorRaw.length === 0))
                      const isRamAxisPhone =
                        (categorySlug === 'smartphones' && (brand === 'samsung' || brand === 'xiaomi')) ||
                        inferredRamAxisPhone ||
                        (isPhoneByName && isMemoryLike(connectivityRaw) && isMemoryLike(storageRaw))
                      const isWatch = categorySlug === 'watches' || categorySlug === 'smart-bands' || /watch/i.test(item.name || '')
                      const nameLower = String(item.name || '').toLowerCase()
                      const procLower = String(attrs.processor || '').toLowerCase()
                      const isLikelyLaptop =
                        categorySlug === 'laptops' ||
                        /macbook|laptop|ноутбук|cpu|gpu|ssd/.test(nameLower) ||
                        /cpu|gpu/.test(procLower)
                      const isLikelyMonoblok = categorySlug === 'monobloki'
                      const isLikelyTablet =
                        categorySlug === 'tablets' ||
                        /ipad|tablet|планшет/.test(nameLower)

                      if (isLikelyMonoblok) {
                        return {
                          storage: normalizeMemoryValue(attrs.storage) || attrs.storage || null,
                          // Monoblock: processor shown as a chip, RAM in connectivity slot
                          connectivity: attrs.processor || null,
                          ram: normalizeMemoryValue(attrs.connectivity) || attrs.connectivity || null,
                          color: item.color || null,
                        }
                      }

                      if (isLikelyLaptop) {
                        return {
                          storage: normalizeMemoryValue(attrs.storage) || attrs.storage || null,
                          // Laptops in group constructor store RAM in `connectivity`.
                          // We hide the generic connectivity axis for this category.
                          connectivity: null,
                          ram: normalizeMemoryValue(attrs.connectivity) || attrs.connectivity || null,
                          color: item.color || null,
                        }
                      }

                      if (isLikelyTablet) {
                        return {
                          storage: normalizeMemoryValue(attrs.storage) || attrs.storage || null,
                          // Tablets store RAM in `connectivity` and network type in `processor`.
                          connectivity: attrs.processor || null,
                          ram: normalizeMemoryValue(attrs.connectivity) || attrs.connectivity || null,
                          color: item.color || null,
                        }
                      }

                      const mappedConnectivity = isRamAxisPhone ? (attrs.processor || null) : (attrs.connectivity || null)
                      const mappedRam = isRamAxisPhone ? (attrs.connectivity || null) : (attrs.processor || null)
                      return {
                        storage: isWatch ? normalizeWatchStrapSize(attrs.storage) : (normalizeMemoryValue(attrs.storage) || attrs.storage || null),
                        connectivity: mappedConnectivity,
                        ram: normalizeMemoryValue(mappedRam) || mappedRam,
                        color: item.color || null,
                      }
                    }
                    const parsed = parseAttrsFromProduct(item.name, item.color)
                    const isWatch = item.category?.slug === 'watches' || item.category?.slug === 'smart-bands' || /watch/i.test(item.name || '')
                    
                    if (isWatch && Object.keys(attrs).length === 0) {
                        let wConn = null;
                        let wStorage = null;
                        let wRam = null;

                        const dialMatch = item.name.match(/(\d{2,}\s*(?:mm|мм))/i) || item.name.match(/\b(32|38|40|41|42|44|45|46|49)\b/);
                        if (dialMatch) wConn = dialMatch[0].trim();

                        const strapSizeMatch = item.name.match(/\b(S\s*\/\s*M|M\s*\/\s*L|ONE\s+SIZE|ЕДИНЫЙ|S|M|L)\b/i);
                        if (strapSizeMatch) wStorage = normalizeWatchStrapSize(strapSizeMatch[0]);

                        let remainder = item.name;
                        if (item.color) {
                            const cleanColor = item.color.replace(/[()]/g, '').trim();
                            const colorWords = cleanColor.split(' ').filter((w: string) => w.length > 2);
                            colorWords.forEach((word: string) => {
                                remainder = remainder.replace(new RegExp(word, 'ig'), '');
                            });
                        }
                        if (wConn) remainder = remainder.replace(new RegExp(wConn.replace(/\s+/g,'\\s*'), 'ig'), '');
                        if (wStorage) remainder = remainder.replace(new RegExp(`\\b${wStorage.replace('/','\\/')}\\b`, 'ig'), '');
                        remainder = remainder.replace(/apple watcheee|apple watch series \d+|apple watch se \d+|apple watch se|apple watch ultra \d+|apple watch ultra|apple watch|watch|часы|\b202\d\b/ig, '');
                        remainder = remainder.replace(/[,\(\)]/g, '').replace(/[\-]/g, ' ');
                        wRam = remainder.replace(/\s+/g, ' ').trim() || null;

                        parsed.connectivity = wConn || parsed.connectivity;
                        parsed.storage = wStorage || parsed.storage;
                        parsed.ram = wRam || parsed.ram;
                        
                        // Clear out generic fallback that put "32" into ram earlier
                        if (parsed.ram === wConn) parsed.ram = null;
                    }

                    // ── Очки: у сиблингов нет attributes → достаём оправу/линзы/размер из
                    // названия «… (FRAME оправа, линзы LENS) SIZE». Значения совпадают с
                    // attributes текущей карточки, поэтому переключатель группы собирает все.
                    if (/оправа/i.test(item.name || '') && Object.keys(attrs).length === 0) {
                        const frameM = item.name.match(/\(\s*([^,()]*?)\s*оправа/i)
                        const lensM = item.name.match(/линз[а-я]*\s*([^)]*)\)/i)
                        const sizeM = item.name.match(/\)\s*(XXL|XL|S\/M|M\/L|ONE\s*SIZE|Единый|S|M|L)\s*$/i)
                        if (frameM) parsed.ram = frameM[1].trim()
                        if (lensM) parsed.storage = lensM[1].trim()
                        if (sizeM) parsed.connectivity = sizeM[1].trim()
                    }
                    return parsed;
                  }

                  const cardsWithAttrs = allCards.map(c => {
                    const parsed = getParsed(c)
                    return { ...c, storage: parsed.storage, connectivity: parsed.connectivity, ram: parsed.ram }
                  })

                  const currentColor = apiProduct.color || null
                  const currentParsed = getParsed(apiProduct)

                  // Detect laptop group: any card name contains "N ГБ SSD"
                  const isLaptopGroup = allCards.some(c => /\d+\s*(?:ГБ|GB|ТБ|TB)\s+SSD/i.test(c.name))
                  const isMonoblokGroup = apiProduct.category?.slug === 'monobloki'
                  // Очки распознаём и по названию (у части карточек не проставлена категория):
                  // «умные очки» / «оправа» встречаются в названии всех очков.
                  const isSmartGlassesGroup = apiProduct.category?.slug === 'umnye-ochki' || /умные\s*очки|оправа/i.test(apiProduct.name || '')
                  const isWatchGroup = apiProduct.category?.slug === 'watches' || apiProduct.category?.slug === 'smart-bands' || /watch/i.test(apiProduct.name || '')
                  const isTvGroup = apiProduct.category?.slug === 'tv'

                  // Unique values per dimension
                  const uniqueColors = [...new Set(allCards.map(c => c.color).filter(Boolean))] as string[]
                  const uniqueStorages = isWatchGroup
                    ? sortWatchStrapSizes(cardsWithAttrs.map(c => c.storage ?? null))
                    : sortStorageValues(
                        [...new Set(cardsWithAttrs.map(c => c.storage).filter(Boolean))] as string[]
                      )
                  const uniqueConn = [...new Set(cardsWithAttrs.map(c => c.connectivity).filter(Boolean))] as string[]
                  const uniqueRam = sortStorageValues(
                    [...new Set(cardsWithAttrs.map(c => c.ram).filter(Boolean))] as string[]
                  )

                  // Navigate to the best-matching sibling
                  const goTo = (
                    wantColor?: string | null,
                    wantStorage?: string | null,
                    wantConn?: string | null,
                    wantRam?: string | null,
                  ) => {
                    const c = wantColor !== undefined ? wantColor : currentColor
                    const s = wantStorage !== undefined ? wantStorage : currentParsed.storage
                    const cn = wantConn !== undefined ? wantConn : currentParsed.connectivity
                    const r = wantRam !== undefined ? wantRam : currentParsed.ram

                    // Try exact → progressively relax
                    const candidates = [
                      cardsWithAttrs.find(p => p.color === c && p.storage === s && p.connectivity === cn && p.ram === r),
                      cardsWithAttrs.find(p => p.color === c && p.storage === s && p.connectivity === cn),
                      cardsWithAttrs.find(p => p.color === c && p.storage === s && p.ram === r),
                      cardsWithAttrs.find(p => p.color === c && p.storage === s),
                      cardsWithAttrs.find(p => p.color === c && p.connectivity === cn),
                      cardsWithAttrs.find(p => p.color === c && p.ram === r),
                      cardsWithAttrs.find(p => p.storage === s && p.connectivity === cn),
                      cardsWithAttrs.find(p => p.storage === s && p.ram === r),
                      wantColor !== undefined && cardsWithAttrs.find(p => p.color === wantColor),
                      wantStorage !== undefined && cardsWithAttrs.find(p => p.storage === wantStorage),
                      wantConn !== undefined && cardsWithAttrs.find(p => p.connectivity === wantConn),
                      wantRam !== undefined && cardsWithAttrs.find(p => p.ram === wantRam),
                    ]
                    const match = candidates.find(
                      (candidate): candidate is typeof cardsWithAttrs[number] =>
                        !!candidate && typeof candidate !== 'boolean' && candidate.id !== apiProduct.id,
                    )
                    if (match) navigate(`/product/${match.slug}`)
                  }

                  return (
                    <div className="mb-6 space-y-5">
                      {/* ── Color ── */}
                      {uniqueColors.length > 0 && (
                        <div>
                          <p className="mb-2 text-sm text-gray-500">
                            Цвет: <span className="font-semibold text-gray-900">{currentColor || '—'}</span>
                          </p>
                          <div className="flex flex-wrap items-center gap-2.5">
                            {uniqueColors.map(color => {
                              const isCurrent = color === currentColor
                              const swatch = getColorSwatch(color)
                              const isLight = swatch ? parseInt(swatch.replace('#', '').slice(0, 2), 16) > 200 : false
                              // Find sibling thumbnail for this color
                              const sibForColor = allCards.find(c => c.color === color)
                              const thumb = sibForColor?.main_image_url

                              return (
                                <button
                                  key={color}
                                  title={color}
                                  onClick={() => !isCurrent && goTo(color)}
                                  className={`group relative flex flex-col items-center gap-1 rounded-xl border-2 p-1.5 transition-all ${
                                    isCurrent
                                      ? 'border-gray-900 bg-gray-50 shadow-sm'
                                      : 'border-gray-200 bg-white hover:border-gray-400 hover:shadow-sm cursor-pointer'
                                  }`}
                                  style={{ minWidth: 56 }}
                                >
                                  {/* Thumbnail or color swatch */}
                                  {thumb && isImageUrl(thumb) ? (
                                    <div className="h-12 w-12 overflow-hidden rounded-lg bg-gray-100">
                                      <img src={getImageUrl(thumb)} alt={color} className="h-full w-full object-contain" />
                                    </div>
                                  ) : swatch ? (
                                    <div
                                      className={`h-12 w-12 rounded-lg ${isLight ? 'ring-1 ring-inset ring-gray-200' : ''}`}
                                      style={{ backgroundColor: swatch }}
                                    />
                                  ) : (
                                    <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gray-100 text-xs text-gray-400">
                                      {color.slice(0, 3)}
                                    </div>
                                  )}
                                  {/* Color name */}
                                  <span className={`max-w-[70px] truncate text-[10px] leading-tight ${
                                    isCurrent ? 'font-semibold text-gray-900' : 'text-gray-500 group-hover:text-gray-700'
                                  }`}>
                                    {color}
                                  </span>
                                </button>
                              )
                            })}
                          </div>
                        </div>
                      )}

                      {/* ── ОЗУ / RAM ── */}
                      {uniqueRam.length > 0 && (
                        <div>
                          <p className="mb-2 text-sm text-gray-500">
                            {isSmartGlassesGroup ? 'Оправа' : isWatchGroup ? 'Тип ремешка' : 'ОЗУ'}: <span className="font-semibold text-gray-900">{currentParsed.ram || '—'}</span>

                          </p>
                          <div className="flex flex-wrap gap-2">
                            {isWatchGroup ? (
                              currentParsed.ram ? (
                                <button
                                  key={currentParsed.ram}
                                  disabled
                                  className="rounded-xl border border-gray-900 bg-gray-900 px-4 py-2 text-sm font-medium text-white shadow-sm"
                                >
                                  {currentParsed.ram}
                                </button>
                              ) : (
                                <span className="text-sm text-gray-400">—</span>
                              )
                            ) : (
                              uniqueRam.map(ramVal => {
                                const isCurrent = ramVal === currentParsed.ram
                                const target = cardsWithAttrs.find(p =>
                                  p.ram === ramVal &&
                                  (p.color === currentColor || !currentColor) &&
                                  (p.storage === currentParsed.storage || !currentParsed.storage)
                                ) || cardsWithAttrs.find(p => p.ram === ramVal)
                                const isAvailable = !!target
                                // Очки: оправа — главный визуальный вариант, рисуем миниатюрой (как цвет у телефонов).
                                if (isSmartGlassesGroup) {
                                  const thumb = target?.main_image_url
                                  return (
                                    <button
                                      key={ramVal}
                                      title={ramVal}
                                      disabled={!isAvailable}
                                      onClick={() => isAvailable && !isCurrent && goTo(undefined, undefined, undefined, ramVal)}
                                      className={`group relative flex flex-col items-center gap-1 rounded-xl border-2 p-1.5 transition-all ${
                                        isCurrent
                                          ? 'border-gray-900 bg-gray-50 shadow-sm'
                                          : isAvailable
                                            ? 'border-gray-200 bg-white hover:border-gray-400 hover:shadow-sm cursor-pointer'
                                            : 'cursor-not-allowed border-gray-100 bg-gray-50 opacity-50'
                                      }`}
                                      style={{ minWidth: 56 }}
                                    >
                                      {thumb && isImageUrl(thumb) ? (
                                        <div className="h-12 w-12 overflow-hidden rounded-lg bg-gray-100">
                                          <img src={getImageUrl(thumb)} alt={ramVal} className="h-full w-full object-contain" />
                                        </div>
                                      ) : (
                                        <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-gray-100 text-xs text-gray-400">
                                          {ramVal.slice(0, 3)}
                                        </div>
                                      )}
                                      <span className={`max-w-[70px] truncate text-[10px] leading-tight ${
                                        isCurrent ? 'font-semibold text-gray-900' : 'text-gray-500 group-hover:text-gray-700'
                                      }`}>
                                        {ramVal}
                                      </span>
                                    </button>
                                  )
                                }
                                return (
                                  <button
                                    key={ramVal}
                                    disabled={!isAvailable}
                                    onClick={() => isAvailable && !isCurrent && goTo(undefined, undefined, undefined, ramVal)}
                                    className={`rounded-xl border px-4 py-2 text-sm font-medium transition-all ${
                                      isCurrent
                                        ? 'border-gray-900 bg-gray-900 text-white shadow-sm'
                                        : isAvailable
                                          ? 'border-gray-200 bg-white text-gray-700 hover:border-gray-400 hover:shadow-sm cursor-pointer'
                                          : 'cursor-not-allowed border-gray-100 bg-gray-50 text-gray-300'
                                    }`}
                                  >
                                    {ramVal}
                                  </button>
                                )
                              })
                            )}
                          </div>
                        </div>
                      )}

                      {/* ── Storage / Память SSD ── */}
                      {uniqueStorages.length > 0 && (
                        <div>
                          <p className="mb-2 text-sm text-gray-500">
                            {isLaptopGroup || isMonoblokGroup ? 'Память SSD' : isSmartGlassesGroup ? 'Линзы' : isWatchGroup ? 'Размер ремешка' : isTvGroup ? 'Диагональ' : 'Память'}: <span className="font-semibold text-gray-900">{currentParsed.storage || '—'}</span>
                          </p>
                          <div className="flex flex-wrap gap-2">
                            {uniqueStorages.map(stor => {
                              const normalizedStor = isWatchGroup ? normalizeWatchStrapSize(stor) : stor
                              const normalizedCurrentStorage = isWatchGroup ? normalizeWatchStrapSize(currentParsed.storage) : currentParsed.storage
                              const isCurrent = normalizedStor === normalizedCurrentStorage
                              const target = cardsWithAttrs.find(p =>
                                (isWatchGroup ? normalizeWatchStrapSize(p.storage) : p.storage) === normalizedStor &&
                                (p.color === currentColor || !currentColor)
                              ) || cardsWithAttrs.find(p =>
                                (isWatchGroup ? normalizeWatchStrapSize(p.storage) : p.storage) === normalizedStor
                              )
                              const isAvailable = !!target
                              return (
                                <button
                                  key={stor ?? '__no_size__'}
                                  disabled={!isAvailable}
                                  onClick={() => isAvailable && !isCurrent && goTo(undefined, normalizedStor ?? null)}
                                  className={`rounded-xl border px-4 py-2 text-sm font-medium transition-all ${
                                    isCurrent
                                      ? 'border-gray-900 bg-gray-900 text-white shadow-sm'
                                      : isAvailable
                                        ? 'border-gray-200 bg-white text-gray-700 hover:border-gray-400 hover:shadow-sm cursor-pointer'
                                        : 'cursor-not-allowed border-gray-100 bg-gray-50 text-gray-300'
                                  }`}
                                >
                                  {stor ?? 'Без размера'}
                                </button>
                              )
                            })}
                          </div>
                        </div>
                      )}

                      {/* ── Connectivity (Связь / SIM) ── */}
                      {uniqueConn.length > 0 && (
                        <div>
                          <p className="mb-2 text-sm text-gray-500">
                            {isSmartGlassesGroup ? 'Размер' : isMonoblokGroup ? 'Процессор' : isWatchGroup ? 'Размер корпуса' : 'Связь'}: <span className="font-semibold text-gray-900">{currentParsed.connectivity || '—'}</span>
                          </p>
                          <div className="flex flex-wrap gap-2">
                            {uniqueConn.map(conn => {
                              const isCurrent = conn === currentParsed.connectivity
                              const target = cardsWithAttrs.find(p =>
                                p.connectivity === conn && (p.color === currentColor || !currentColor)
                              ) || cardsWithAttrs.find(p => p.connectivity === conn)
                              const isAvailable = !!target

                              return (
                                <button
                                  key={conn}
                                  disabled={!isAvailable}
                                  onClick={() => isAvailable && !isCurrent && goTo(undefined, undefined, conn)}
                                  className={`rounded-xl border px-4 py-2 text-sm font-medium transition-all ${
                                    isCurrent
                                      ? 'border-gray-900 bg-gray-900 text-white shadow-sm'
                                      : isAvailable
                                        ? 'border-gray-200 bg-white text-gray-700 hover:border-gray-400 hover:shadow-sm cursor-pointer'
                                        : 'cursor-not-allowed border-gray-100 bg-gray-50 text-gray-300'
                                  }`}
                                >
                                  {conn}
                                </button>
                              )
                            })}
                          </div>
                        </div>
                      )}
                    </div>
                  )
                })()}

                {/* Variant selector — only show when product is NOT in a group */}
                {variants.length > 0 && !(apiProduct.siblings && apiProduct.siblings.length > 0) && (() => {
                  const isWatchGroup = apiProduct.category?.slug === 'watches' || apiProduct.category?.slug === 'smart-bands' || /watch/i.test(apiProduct.name || '')
                  const isTvGroup = apiProduct.category?.slug === 'tv'
                  const colors = [...new Set(variants.filter(v => v.color).map(v => v.color!))]
                  const storages = [...new Set(variants.filter(v => v.storage).map(v => v.storage!))]
                  const sizes = [...new Set(variants.filter(v => v.size).map(v => v.size!))]

                  // Which storages exist for the currently selected color?
                  const availableStorages = selectedColor
                    ? [...new Set(variants.filter(v => v.color === selectedColor && v.storage).map(v => v.storage!))]
                    : storages

                  // Which sizes exist for the currently selected color+storage?
                  const availableSizes = [...new Set(variants.filter(v =>
                    (!selectedColor || v.color === selectedColor) &&
                    (!selectedStorage || v.storage === selectedStorage) &&
                    v.size
                  ).map(v => v.size!))]

                  // Click color → auto-fix storage/size if they become incompatible
                  const handleColorSelect = (color: string) => {
                    setSelectedColor(color)
                    setStockWarning(null)
                    setQuantity(1)
                    setActiveImageIndex(0) // Reset to first image when color changes
                    const storagesForColor = [...new Set(
                      variants.filter(v => v.color === color && v.storage).map(v => v.storage!)
                    )]
                    if (storagesForColor.length > 0 && selectedStorage && !storagesForColor.includes(selectedStorage)) {
                      setSelectedStorage(storagesForColor[0])
                    }
                    const sizesForColor = [...new Set(
                      variants.filter(v => v.color === color && v.size).map(v => v.size!)
                    )]
                    if (sizesForColor.length > 0 && selectedSize && !sizesForColor.includes(selectedSize)) {
                      setSelectedSize(sizesForColor[0])
                    }
                  }

                  // CSS swatch map — reuse shared map
                  return (
                    <div className="mb-5 space-y-4">
                      {/* ── Colors (hide when siblings handle color switching) ── */}
                      {colors.length > 0 && !(apiProduct.siblings && apiProduct.siblings.length > 0) && (
                        <div>
                          <p className="mb-2.5 text-[13px] text-gray-500">
                            Цвет: <span className="font-semibold text-gray-900">{selectedColor || colors[0]}</span>
                          </p>
                          <div className="flex flex-wrap gap-2">
                            {colors.map(c => {
                              const swatch = getColorSwatch(c)
                              const isActive = selectedColor === c
                              const isLight = swatch
                                ? parseInt(swatch.replace('#','').slice(0,2), 16) > 200
                                : false
                              return swatch ? (
                                <button
                                  key={c}
                                  title={c}
                                  onClick={() => handleColorSelect(c)}
                                  style={{ backgroundColor: swatch }}
                                  className={`h-7 w-7 flex-shrink-0 rounded-full transition-all ${
                                    isActive
                                      ? 'ring-[3px] ring-offset-[3px] ring-gray-800 scale-110'
                                      : 'ring-1 ring-transparent hover:scale-105 hover:ring-gray-300'
                                  } ${isLight ? 'ring-1 ring-gray-300' : ''}`}
                                />
                              ) : (
                                <button
                                  key={c}
                                  onClick={() => handleColorSelect(c)}
                                  className={`rounded-full border px-3 py-1 text-sm transition-all ${
                                    isActive
                                      ? 'border-gray-900 bg-gray-900 text-white'
                                      : 'border-gray-300 bg-white text-gray-700 hover:border-gray-400'
                                  }`}
                                >
                                  {c}
                                </button>
                              )
                            })}
                          </div>
                        </div>
                      )}

                      {/* ── Storage (накопитель) — disabled if not in current color ── */}
                      {storages.length > 0 && (
                        <div>
                          <p className="mb-2.5 text-[13px] text-gray-500">{isWatchGroup ? 'Размер ремешка' : isTvGroup ? 'Диагональ' : 'Накопитель'}</p>
                          <div className="flex flex-wrap gap-2">
                            {storages.map(s => {
                              const isAvailable = availableStorages.includes(s)
                              const isActive = selectedStorage === s
                              return (
                                <button
                                  key={s}
                                  disabled={!isAvailable}
                                  onClick={() => isAvailable && (setSelectedStorage(s), setStockWarning(null), setQuantity(1))}
                                  className={`rounded-full border px-4 py-1.5 text-sm font-medium transition-all ${
                                    isActive && isAvailable
                                      ? 'border-gray-900 bg-gray-900 text-white'
                                      : isAvailable
                                        ? 'border-gray-300 bg-white text-gray-700 hover:border-gray-400'
                                        : 'cursor-not-allowed border-gray-200 bg-white text-gray-300 line-through'
                                  }`}
                                >
                                  {s}
                                </button>
                              )
                            })}
                          </div>
                        </div>
                      )}

                      {/* ── Size / SIM — disabled if not in current color+storage ── */}
                      {sizes.length > 0 && (
                        <div>
                          <p className="mb-2.5 text-[13px] text-gray-500">{isWatchGroup ? 'Размер корпуса' : 'Связь'}</p>
                          <div className="flex flex-wrap gap-2">
                            {sizes.map(s => {
                              const isAvailable = availableSizes.includes(s)
                              const isActive = selectedSize === s
                              return (
                                <button
                                  key={s}
                                  disabled={!isAvailable}
                                  onClick={() => isAvailable && (setSelectedSize(s), setStockWarning(null), setQuantity(1))}
                                  className={`rounded-full border px-4 py-1.5 text-sm font-medium transition-all ${
                                    isActive && isAvailable
                                      ? 'border-gray-900 bg-gray-900 text-white'
                                      : isAvailable
                                        ? 'border-gray-300 bg-white text-gray-700 hover:border-gray-400'
                                        : 'cursor-not-allowed border-gray-200 bg-white text-gray-300 line-through'
                                  }`}
                                >
                                  {s}
                                </button>
                              )
                            })}
                          </div>
                        </div>
                      )}
                    </div>
                  )
                })()}

                {/* Standalone product attrs (no group, no variants) */}
                {variants.length === 0 && !(apiProduct.siblings && apiProduct.siblings.length > 0) && (() => {
                  const attrs = apiProduct.attributes || {}
                  const rows: { label: string; value: string | null }[] = []

                  if (apiProduct.color) rows.push({ label: 'Цвет', value: apiProduct.color })
                  const labels = new Map(categoryFields.map(field => [field.key, field.label]))
                  Object.entries(attrs).forEach(([key, value]) => {
                    if (value === null || value === undefined || value === '') return
                    rows.push({ label: labels.get(key) || key.replace(/_/g, ' '), value: typeof value === 'boolean' ? (value ? 'Да' : 'Нет') : String(value) })
                  })

                  if (rows.length === 0) return null
                  return (
                    <div className="mb-5 space-y-2">
                      {rows.map(({ label, value }) => value ? (
                        <div key={label}>
                          <span className="text-sm text-gray-500">{label}: </span>
                          <span className="text-sm font-semibold text-gray-900">{value}</span>
                        </div>
                      ) : null)}
                    </div>
                  )
                })()}

                {/* Price */}
                <div className="mb-6 flex items-end gap-3">
                  <span className="text-3xl font-bold text-gray-900 sm:text-4xl">
                    {formatPrice(Number(effectivePrice))}
                  </span>
                  {effectiveOldPrice != null && (
                    <span className="mb-1 text-xl text-gray-400 line-through">
                      {formatPrice(Number(effectiveOldPrice))}
                    </span>
                  )}
                </div>
                
                {/* Description removed from right column — shown in tab below */}
                
                {/* Actions */}
                <div className="mb-8 space-y-3">
                  {/* Quantity + Buy row */}
                  <div className="flex flex-wrap items-center gap-3">
                    {/* Quantity selector */}
                    <div className="flex items-center rounded-xl border border-gray-200 bg-white">
                      <button
                        onClick={() => { setStockWarning(null); setQuantity(q => Math.max(1, q - 1)) }}
                        className="flex h-10 w-10 items-center justify-center text-lg font-medium text-gray-500 transition-colors hover:text-gray-900"
                        disabled={quantity <= 1}
                      >
                        −
                      </button>
                      <span className="w-6 text-center text-base font-semibold">{quantity}</span>
                      <button
                        onClick={() => {
                          if (quantity >= effectiveStock) {
                            setStockWarning(`К сожалению, товар закончился. Вы можете заказать только ${effectiveStock} шт. или выбрать другой товар.`)
                          } else {
                            setStockWarning(null)
                            setQuantity(q => q + 1)
                          }
                        }}
                        className="flex h-10 w-10 items-center justify-center text-lg font-medium text-gray-500 transition-colors hover:text-gray-900"
                      >
                        +
                      </button>
                    </div>

                    {/* Add to cart button */}
                    <button
                      onClick={handleAddToCart}
                      disabled={effectiveStock <= 0}
                      className="flex-1 rounded-xl bg-yellow-400 px-6 py-3 text-sm font-semibold text-gray-900 shadow-sm transition-all hover:bg-yellow-500 hover:shadow-md active:scale-[0.98] disabled:bg-gray-200 disabled:text-gray-400 disabled:shadow-none sm:text-base sm:py-3.5"
                    >
                      Добавить в корзину
                    </button>

                    {/* Call button */}
                    <a
                      href="tel:+79998021022"
                      className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm font-medium text-gray-700 transition-all hover:bg-gray-50 active:scale-[0.98] sm:py-3.5"
                    >
                      📞 Позвонить
                    </a>
                  </div>
                  {stockWarning && (
                    <div className="rounded-lg bg-orange-50 border border-orange-200 px-4 py-3 text-sm text-orange-800">
                      {stockWarning}
                    </div>
                  )}
                </div>
                
                {/* Disclaimer */}
                <p className="mb-6 text-xs text-gray-400">
                  {apiProduct?.brand?.toLowerCase() === 'apple' && (
                    <>
                      Товар имеет недостаток: невозможно установить и использовать RuStore
                      <br />
                    </>
                  )}
                  Цена действительна только для интернет-магазина и может отличаться от цен в розничных магазинах,
                  а также в зависимости от версии приобретаемого устройства
                </p>
                
                {/* Benefits */}
                <div className="grid gap-4 rounded-2xl bg-gray-50 p-6 sm:grid-cols-2">
                  <div className="flex items-start gap-3">
                    <div className="rounded-lg bg-yellow-100 p-2 text-yellow-600">
                      <TruckIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <div className="font-semibold text-gray-900">Быстрая доставка</div>
                      <div className="text-sm text-gray-500">По Москве от 30 мин</div>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <div className="rounded-lg bg-green-100 p-2 text-green-600">
                      <ShieldIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <div className="font-semibold text-gray-900">Гарантия 1 год</div>
                      <div className="text-sm text-gray-500">Официальная</div>
                    </div>
                  </div>
                </div>
                
                {/* Call to order */}
                <div className="mt-6 flex items-center gap-4 rounded-2xl border border-yellow-200 bg-yellow-50 p-4">
                  <div className="rounded-full bg-yellow-400 p-3">
                    <PhoneIcon className="h-6 w-6 text-gray-900" />
                  </div>
                  <div>
                    <div className="text-sm text-gray-600">Остались вопросы?</div>
                    <a href="tel:+79998021022" className="text-lg font-semibold text-gray-900 hover:text-yellow-600">
                      +7 (999) 802-10-22
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </section>
        
        {/* Tabs Section */}
        <section className="border-t border-gray-100 bg-white py-8">
          <Container>
            {/* Tab buttons */}
            <div className="mb-6 flex gap-1 overflow-x-auto rounded-xl bg-gray-100 p-1">
              {[
                { id: 'description', label: 'Описание' },
                { id: 'specs', label: 'Характеристики' },
              ].map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as typeof activeTab)}
                  className={`flex-1 whitespace-nowrap rounded-lg px-6 py-3 text-sm font-semibold transition-colors ${
                    activeTab === tab.id
                      ? 'bg-white text-gray-900 shadow-sm'
                      : 'text-gray-600 hover:text-gray-900'
                  }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>
            
            {/* Tab content */}
            <div className="rounded-2xl border border-gray-100 bg-white p-6">
              {activeTab === 'description' && (
                <div className="prose max-w-none">
                  <p className="text-gray-600 leading-relaxed">{apiProduct.description}</p>
                  <p className="mt-4 text-gray-600 leading-relaxed">
                    {apiProduct.brand} — один из ведущих мировых брендов электроники. 
                    Продукция отличается высоким качеством сборки, инновационными технологиями 
                    и долгим сроком службы.
                  </p>
                </div>
              )}
              
              {activeTab === 'specs' && (() => {
                // Схема категории даёт человеческие подписи атрибутам; color уже показан
                // отдельной строкой, поэтому из attributes его не дублируем.
                const labels = new Map(categoryFields.map(field => [field.key, field.label]))
                const attrSpecs = Object.entries(apiProduct.attributes || {})
                  .filter(([key, value]) => key !== 'color' && value !== null && value !== undefined && value !== '')
                  .map(([key, value]) => ({
                    label: labels.get(key) || key.replace(/_/g, ' '),
                    value: typeof value === 'boolean' ? (value ? 'Да' : 'Нет') : String(value),
                  }))
                const rows = ([
                  apiProduct.brand ? { label: 'Бренд', value: apiProduct.brand } : null,
                  apiProduct.model ? { label: 'Модель', value: apiProduct.model } : null,
                  apiProduct.color ? { label: 'Цвет', value: apiProduct.color } : null,
                  ...attrSpecs,
                  apiProduct.sku ? { label: 'Артикул', value: apiProduct.sku } : null,
                  apiProduct.warranty_months ? { label: 'Гарантия', value: `${apiProduct.warranty_months} мес.` } : null,
                ] as Array<{label: string; value: string} | null>).filter((x): x is {label: string; value: string} => x !== null)
                return (
                  <div className="divide-y divide-gray-100">
                    {rows.map((spec, i) => (
                      <div key={i} className="flex justify-between py-4 first:pt-0 last:pb-0">
                        <span className="text-gray-500">{spec.label}</span>
                        <span className="font-medium text-gray-900">{spec.value}</span>
                      </div>
                    ))}
                  </div>
                )
              })()}
            </div>
          </Container>
        </section>
        
        {/* CTA */}
        <section className="bg-gradient-to-r from-yellow-400 to-amber-400 py-12">
          <Container>
            <div className="flex flex-col items-center gap-6 text-center sm:flex-row sm:justify-between sm:text-left">
              <div>
                <h2 className="mb-2 text-2xl font-bold text-gray-900">Нужна консультация?</h2>
                <p className="text-gray-800">Наши специалисты ответят на все ваши вопросы</p>
              </div>
              <Button href="https://t.me/takesmart_manager" variant="secondary" size="lg">
                Написать менеджеру
              </Button>
            </div>
          </Container>
        </section>
      </div>
    )
}
